### ISSUE TITLE
Just says no reviews

### ISSUE THREAD

**Issue by stefijugo** [ashercs/SpicetifyAOTYScores#4]
it just says no reviews for any song

**Comment by xBenjo** [comment]
I'm having the same problem but the console won't open no matter what I do

**Comment by ashercs** [comment]
@xBenjo as in inspect element is already open but you just cannot click on the console section on it?

**Comment by xBenjo** [comment]
No, I can't get inspect element to open. I've had the console open before but now it doesn't work. I've tried enabling dev tool again but none of the commands are recognized

**Comment by xBenjo** [comment]
I am in the console now, what am I looking for?
![image](https://github.com/ashercs/SpicetifyAOTYScores/assets/138199616/8212933d-fca4-46be-b58a-d525cb272f2b)
![image](https://github.com/ashercs/SpicetifyAOTYScores/assets/138199616/d80e48ac-0450-4977-bd0d-dd55bdb39f92)
Please lmk if there is a console export funtion I will send that to you if needed

**Comment by ashercs** [comment]
Odd, doesn't seem to be anything there, does the albumoftheyear.org site work when you go to it?

**Comment by xBenjo** [comment]
Yeah the site still works.
I'm also not getting the score not found error when trying to refresh score. It seems like its not even looking for info on the website anymore.

**Comment by xBenjo** [comment]
Yeah both spicetify and spotify are fully updated, but I think it was the spotify updates that slowly broke the extension

**Comment by ashercs** [comment]
This should be working now. If any issues arise, reopen this issue. Appreciate the patience.

**Comment by xBenjo** [comment]
![image](https://github.com/ashercs/SpicetifyAOTYScores/assets/138199616/024a2639-cd71-4a1e-9ddb-2823bdd73615)
after redownloading the extension I'm getting this error and no scores
