### ISSUE TITLE
support for rateyourmusic

### ISSUE THREAD

**Issue by newBonfire** [ashercs/SpicetifyAOTYScores#6]
It would be great if you could expand support for [rateyourmusic](https://rateyourmusic.com) ?
there is an [extension](https://github.com/eatsfoobars/spicetify-rym) which stopped working for me.

**Comment by ashercs** [comment]
I made this as an alternative version for that extension. I'd create an issue on that repository and see if it gets fixed. If not, and that repo is inactive I may consider implementing it to this at some point in the future.
