### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by OketZzz** [ashercs/SpicetifyAOTYScores#7]
stopped working like 2 months ago, i did everything still nothing showing up

**Comment by arbuzavr** [comment]
Unfortunately, not working for me either for a month or so. Probably my favourite spicetify extension - please fix it!

**Comment by ashercs** [comment]
Alright, I discovered the issue, turns out the new Spotify GUI made it stop working, I wasn't aware of this since I was using the old one, when I updated it stopped working, I'll have a fix in for this shortly, sorry for not noticing this earlier.

**Comment by OketZzz** [comment]
thanks man 🫡

**Comment by ashercs** [comment]
Ideally this will be fixed over the weekend, thanks for your patience.

**Comment by ashercs** [comment]
This should be working now. If any issues arise, reopen this issue. Appreciate the patience.

**Comment by OketZzz** [comment]
yup still not working
