### ISSUE TITLE
Still not working

### ISSUE THREAD

**Issue by arbuzavr** [ashercs/SpicetifyAOTYScores#8]
Unfortunately, even after reinstalling the extension and resetting Spicetify, it still doesn't work for me. Refresh Score and Clear Score buttons are up there, but the score itself is nowhere to be found.

_Originally posted by @arbuzavr in https://github.com/ashercs/SpicetifyAOTYScores/issues/7#issuecomment-1733214405_

**Comment by ashercs** [comment]
Run `spicetify enable-devtools` then see if anything shows up in the console. Also if you wouldn’t mind a screenshot of what your Spotify looks like just so I know if the GUI is the same. Make sure to update Spotify as well as that *might* fix it.

**Comment by arbuzavr** [comment]
![image](https://github.com/ashercs/SpicetifyAOTYScores/assets/108761453/09554c07-20da-4cd1-804c-e02b143a3c72)
![image](https://github.com/ashercs/SpicetifyAOTYScores/assets/108761453/a11b46bb-e9ba-48d9-864d-286eac459159)
![image](https://github.com/ashercs/SpicetifyAOTYScores/assets/108761453/a8724750-7241-44fc-9359-633249f0f18f)

oh yes, it shows errors in the console for the extension. I've made the screenshots you requested. The Spotify client app is up-to-date.

**Comment by ashercs** [comment]
Sorry for not seeing this for some time, was on a school trip. I'll work on a fix for this soon, should be in by Tuesday.

**Comment by ashercs** [comment]
I figured out the error I made. It should be fixed. Sorry again for the wait.

**Comment by arbuzavr** [comment]
can confirm it is working properly now. Big props for fixing it!
